{
 "title": "Observability Accelerator OpenSearch",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.labels.app_kubernetes_io/name.keyword\"}"
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "entries" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.labels.app_kubernetes_io/name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/name.keyword: $name AND *$filter*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Entries",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.labels.app_kubernetes_io/name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/name: $name AND *$filter*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.labels.app_kubernetes_io/name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/name.keyword: $name AND error AND *$filter*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.labels.app_kubernetes_io/name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/name.keyword: $name AND warn AND NOT error AND *$filter*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}